discord:
  urls:
    all: ${DISCORD_DEV}
    student: ${DISCORD_DEV}
    normal: ${DISCORD_DEV}
    scholarship: ${DISCORD_DEV}
    sim-com: ${DISCORD_DEV}
    gl-sop: ${DISCORD_DEV}
    graduate: ${DISCORD_DEV}
    graduate-contract: ${DISCORD_DEV}

server:
  port: ${PORT}

springdoc:
  swagger-ui:
    path: swagger.html
    operations-sorter: method
  #  version: v1
  paths-to-match: /api/**

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: debug
  config:
    path: ${LOGGING_PATH}